/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC12_1.h"
#include "LCD_1.h"
#include "LED_1.h"
#include "LED_2.h"
#include "LED_3.h"
#include "LED_4.h"
#include "PGA_1.h"
#include "Timer16_1.h"
#include "Timer16_2.h"
#include "Timer32_1.h"

#endif
