PROJNAME=SoundBasedStopwatch
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=D:/CypressProjects/SoundBasedStopwatch/SoundBasedStopwatch/SoundBasedStopwatch
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.3/Common/CY110F~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.3/Common/CY110F~1/tools/include/CY8C29~1
CSRCS=
LIBCSRCS=
STDCSRCS=
ASMSRCS= accuracymode.asm delay.asm main.asm memorymode.asm soundsensitivitymode.asm soundstopwatchmode.asm stopwatchmode.asm storingtomemory.asm
LIBASMSRCS= adcinc12_1.asm adcinc12_1int.asm lcd_1.asm led_1.asm led_2.asm led_3.asm led_4.asm pga_1.asm psocconfig.asm psocconfigtbl.asm psocgpioint.asm timer16_1.asm timer16_1int.asm timer16_2.asm timer16_2int.asm timer32_1.asm timer32_1int.asm
STDASMSRCS=
OBJECT_SOURCES= accuracymode.asm delay.asm main.asm memorymode.asm soundsensitivitymode.asm soundstopwatchmode.asm stopwatchmode.asm storingtomemory.asm
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=timer1 
